language: elixir
script: "mix travis-ci"
after_success: "bash <(curl -s https://codecov.io/bash)"
jobs:
  include:
    - elixir: 1.10
      otp_release: 23.0
    - elixir: 1.10
      otp_release: 22.2
    - elixir: 1.10
      otp_release: 22.1
    - elixir: 1.9
      otp_release: 22.3
    - elixir: 1.9
      otp_release: 22.2
    - elixir: 1.9
      otp_release: 22.1
