language: elixir
script: "mix travis-ci"
install: "sudo pip install codecov"
after_success: "codecov --file cover/excoveralls.xml"
jobs:
  include:
    - elixir: 1.10
      otp_release:
        - 23.0
        - 22.2
        - 22.1
    - elixir: 1.9
      otp_release:
        - 22.3
        - 22.2
        - 22.1
